CHY_Project/CHY_Project/Models/Song.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CHY_Project.Models
{
    public class Song : Product
    {
        [Key]
        public String SongID { get; set; }

        [Required]
        [Display(Name ="Song Name")]
        public String SongName { get; set; }

        [Required]
        public virtual List<Artist> Artists { get; set;}

        public virtual Album Album { get; set; }

        public Song()
        {
            Genres = new List<Genre>();
            Artists = new List<Artist>();
        }
    }
}

CHY_Project/CHY_Project/Models/SongViewModel.cs
using System;
using System.Collections.Generic;

using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


using CHY_Project.Models;


namespace CHY_Project.Models
{
    public class SongViewModel
    {

        public Int32 id { get; set; }
        [Display(Name = "Song Name")]
        public String SongName { get; set; }

        public virtual List<Artist> Artists { get; set; }

        public virtual Album Album { get; set; }

        public Decimal RegularPrice { get; set; }

        public Decimal DiscountPrice { get; set; }

        public decimal AvgRating { get; set; }

        public virtual List<Song> Songs { get; set; }
        public virtual List<Rating> Ratings { get; set; }


    }
}

CHY_Project/CHY_Project/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CHY_Project.Models;
using System.Globalization;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace CHY_Project.Controllers
{
    public class SongsController : Controller
    {
        public enum SongSort { Name, Artist, Rating}
        public enum SortOrder { Ascending, Descending}

        private AppDbContext db = new AppDbContext();

        // GET: Songs
        public ActionResult Index()
        {
            List<Song> AllSongs = db.Songs.ToList();

            ViewBag.SongCount = CountSongs(AllSongs);
            ViewBag.TotalSongCount = CountSongs(AllSongs);
            return View(db.Songs.ToList());
        }

        // GET: Songs/Details/5
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Songs.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }

            //Set the song's properties
            SongDetailsViewModel songvm = new SongDetailsViewModel();
            songvm.SongName = song.SongName;
            songvm.ContentID = song.ContentID;
            songvm.RegularPrice = song.RegularPrice;
            songvm.DiscountPrice = song.DiscountPrice;
            songvm.Featured = song.Featured;
            foreach (Artist artist in song.Artists)
            {
                songvm.Artists.Add(artist);
            }

            songvm.Album = song.Album;

            foreach (Genre genre in song.Genres)
            {
                songvm.Genres.Add(genre);
            }

            return View(songvm);
        }

        //POST: Songs/Details/5
        [HttpPost]
        public ActionResult Details(SongDetailsViewModel model, int id)
        {
            //TODO: Add logic that only allows users with this song in their library to rate/comment
            if(model.Stars != null)
            {
                //Set the Rating's properties
                string username = User.Identity.GetUserName();
                AppUser currentuser = db.Users.FirstOrDefault(u => u.UserName == username);
                Rating rating = new Rating();
                rating.Customer = currentuser;
                rating.Stars = Convert.ToInt32(model.Stars); //TODO: round this maybe?
                if (model.Comment != null)
                {
                    rating.Comment = model.Comment;
                }
                rating.Content = model.Item;
                db.Ratings.Add(rating);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Manager")]
        // GET: Songs/Create
        public ActionResult Create()
        {

            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllArtists = GetAllArtists();
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ContentID,RegularPrice,DiscountPrice,Featured,SongName")] Song song, Int32[] Artists, Int32[] Genres)
        {
            
            if (Artists != null)
            {
                foreach (int Id in Artists)
                {
                    //Artist artist = new Artist();
                   // Artist artist = db.Artists.FirstOrDefault(i => i.ArtistID == Id);
                    Artist artist = db.Artists.Find(Id);
                    song.Artists.Add(artist);
                }
            }

            if (Genres != null)
            {

                //song.Genres = new List<Genre>();
                foreach (int Id in Genres)
                {
                    Genre genre = db.Genres.Find(Id);
                    song.Genres.Add(genre);
                }
            }
            
            Guid songproductGUID = Guid.NewGuid();
            String stringsongproductGUID = songproductGUID.ToString();

            Guid guidSongID = Guid.NewGuid();
            String stringguidsongID = guidSongID.ToString();

            song.ProductID = stringsongproductGUID;
            song.SongID = stringguidsongID;
            //ModelState.SetModelValue("ProductID", new ValueProviderResult(stringsongproductGUID, stringsongproductGUID, CultureInfo.InvariantCulture));
            //ModelState.SetModelValue("SongID", new ValueProviderResult(stringguidsongID, stringguidsongID, CultureInfo.InvariantCulture));


            if (ModelState.IsValid)
            {

                db.Songs.Add(song);
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllArtists = GetAllArtists();
            return View(song);
        }
        [Authorize(Roles = "Manager")]
        // GET: Songs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Songs.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            ViewBag.AllGenres = GetAllGenres(song);
            ViewBag.AllArtists = GetAllArtists(song);
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ContentID,RegularPrice,DiscountPrice,Featured,SongName")] Song song, Int32[] Artists, Int32[] Genres)
        {
            if (ModelState.IsValid)
            {
                Song songToChange = db.Songs.Find(song.ContentID);
                songToChange.Genres.Clear();
                songToChange.Artists.Clear();

                if (Artists != null)
                {
                    foreach (int Id in Artists)
                    {
                        //Artist artist = db.Artists.FirstOrDefault(i => i.ArtistID == Id);
                        Artist artist = db.Artists.Find(Id);
                        songToChange.Artists.Add(artist);
                    }
                }
                if (Genres != null)
                {
                    //song.Genres = new List<Genre>();
                    foreach (int Id in Genres)
                    {
                        Genre genre = db.Genres.Find(Id);
                        songToChange.Genres.Add(genre);
                    }
                }

                songToChange.RegularPrice = song.RegularPrice;
                songToChange.DiscountPrice = song.DiscountPrice;
                songToChange.Featured = song.Featured;
                songToChange.SongName = song.SongName;

                db.Entry(songToChange).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AllGenres = GetAllGenres(song);
            ViewBag.AllArtists = GetAllArtists(song);
            return View(song);
        }
        [Authorize(Roles = "Manager")]
        // GET: Songs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Songs.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }
        [Authorize(Roles = "Manager")]
        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Song song = db.Songs.Find(id);
            
            foreach(Genre genre in song.Genres)
            {
                genre.Contents.Remove(song);
            }
            

            foreach(Artist artist in song.Artists)
            {
                artist.Songs.Remove(song);
            }


            db.Songs.Remove(song);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //Song Search
        public ActionResult Search()
        {
            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllArtists = GetAllArtists();
            //TODO: Write a get all albums method (?)
            //ViewBag.AllAlbums = GetAllAlbums();
            return View();
        }

        //Search Results
        public ActionResult SearchResults(string NameSearchString, string ArtistSearchString, string AlbumSearchString, Int32[] SelectedGenres, SongSort SelectedSort, SortOrder SelectedSortOrder/*, TODO: Add parameter for Rating, once that is set up*/)
        {
            List<Song> SelectedSongs = new List<Song>();
            List<Song> AllSongs = db.Songs.ToList();

            var query = from s in db.Songs
                        select s;

            var qtest = query;

            if (NameSearchString != null && NameSearchString != "")
            {
                query = query.Where(s => s.SongName.Contains(NameSearchString));
            }

CHY_Project/CHY_Project/Views/Songs/Create.cshtml
@model CHY_Project.Models.Song

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     

        <div class="form-group">
            @Html.LabelFor(model => model.SongName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SongName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SongName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegularPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegularPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegularPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscountPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiscountPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiscountPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Featured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Featured)
                    @Html.ValidationMessageFor(model => model.Featured, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Artists, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Artists", (MultiSelectList)ViewBag.AllArtists, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Genres", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CHY_Project/CHY_Project/Views/Songs/Delete.cshtml
@model CHY_Project.Models.Song

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Song</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.RegularPrice)
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.RegularPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscountPrice)
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.DiscountPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Featured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Featured)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.SongName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SongName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CHY_Project/CHY_Project/Views/Songs/Details.cshtml
@model CHY_Project.Models.SongDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Song Details</h2>

@using (Html.BeginForm())
{
    <div>
        <h4>@Html.DisplayFor(model => model.SongName)</h4>
        <hr />
        @Html.ActionLink("Add to Cart", "AddtoCart", "Carts", new { id = Model.ContentID }, null)
        <table class="table table-bordered">
            <tr>
                <th>
                    Artists
                </th>
            </tr>
            @foreach (var artist in Model.Artists)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => artist.ArtistName)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", "Artists", new { id = artist.ContentID }, null)
                    </td>
                </tr>
            }
        </table>

    

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.SongName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SongName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RegularPrice)
            </dt>

            <dd>
                $@Html.DisplayFor(model => model.RegularPrice)
            </dd>

            @if (Model.DiscountPrice < Model.RegularPrice)
            {
                <dt>
                    @Html.DisplayNameFor(model => model.DiscountPrice)
                </dt>

                <dd>
                    $@Html.DisplayFor(model => model.DiscountPrice)
                </dd>
            }

            <dt>
                @Html.DisplayNameFor(model => model.Featured)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Featured)
            </dd>


        </dl>

        <table class="table table-striped">
            <tr>
                <th>
                    Album
                </th>
            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Album.AlbumName)
                </td>
                @if (Model.Album != null)
                {
                <td>
                    @Html.ActionLink("Details", "Details", "Albums", new { id = Model.Album.ContentID }, null)
                </td>
                }
            </tr>
        </table>

        <table class="table table-bordered">
            <tr>
                <th>
                    Genres
                </th>
            </tr>
            @foreach (var genre in Model.Genres)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => genre.GenreName)
                    </td>
                </tr>
            }
        </table>
    </div>


    @Html.LabelFor(model => model.Stars, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Stars, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Stars, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Add Review" />
        </div>
    </div>
}


<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ContentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CHY_Project/CHY_Project/Views/Songs/Edit.cshtml
@model CHY_Project.Models.Song

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Song</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ContentID)

        <div class="form-group">
            @Html.LabelFor(model => model.SongName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SongName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SongName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegularPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegularPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegularPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscountPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiscountPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiscountPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Featured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Featured)
                    @Html.ValidationMessageFor(model => model.Featured, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Artists, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Artists", (MultiSelectList)ViewBag.AllArtists, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Genres", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CHY_Project/CHY_Project/Views/Songs/Index.cshtml
@model IEnumerable<CHY_Project.Models.Song>

@{
    ViewBag.Title = "Index";
}

<h2>Songs</h2>

<h3> Displaying @ViewBag.SongCount of @ViewBag.TotalSongCount Results</h3>
<p>
@Html.ActionLink("Search Songs", "Search", null, new { @class = "btn btn-default" })
</p>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SongName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Artists.First().ArtistName)
        </th>
        <th>
            Price
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SongName)
            </td>
            @*@foreach (var artist in item.Artists)
            {
                <td>
                    @Html.DisplayFor(modelItem => artist.ArtistName)
               </td>

            }*@

            @*NOTE: I changed this to the below so that it didn't mess up formatting by having a list of artists in one field. We can change it back if need be.*@

            <td>
                @Html.DisplayFor(modelItem => item.Artists.First().ArtistName)
            </td>

            <td>
                $@Html.DisplayFor(modelItem => item.DiscountPrice)
            </td>



            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ContentID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ContentID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ContentID }) |
                @Html.ActionLink("Add to Cart", "AddtoCart", "Carts", new { id = item.ContentID }, null)
            </td>
        </tr>
    }
</table>

CHY_Project/CHY_Project/Views/Songs/Search.cshtml
@using CHY_Project.Controllers
@model CHY_Project.Models.Song

@{
    ViewBag.Title = "Song Search";
}

<h2>Song Search</h2>

@using (Html.BeginForm("SearchResults", "Songs", FormMethod.Get))
{
    <p class="form-group">
        Song Title @Html.TextBox("NameSearchString", null, new { @class = "form-control" }) <br />
        Artist @Html.TextBox("ArtistSearchString", null, new { @class = "form-control" }) <br />
        Album @Html.TextBox("AlbumSearchString", null, new { @class = "form-control" }) <br />

        <div class="form-control">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("SelectedGenres", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            Sort By
            <div class="form-check">
                @Html.RadioButton("SelectedSort", SongsController.SongSort.Name, true, new { @class = "form-check-input" }) Name
            </div>
            <div class="form-check">
                @Html.RadioButton("SelectedSort", SongsController.SongSort.Artist, new { @class = "form-check-input" }) Artist
            </div>
            <div class="form-check">
                @Html.RadioButton("SelectedSort", SongsController.SongSort.Rating, new { @class = "form-check-input" }) Rating
            </div>
        </div>

        <div class="form-group">
            Order
            <div class="form-check">
                @Html.RadioButton("SelectedSortOrder", SongsController.SortOrder.Ascending, true, new { @class = "form-check-input" }) Ascending
            </div>
            <div class="form-check">
                @Html.RadioButton("SelectedSortOrder", SongsController.SortOrder.Descending, new { @class = "form-check-input" }) Descending
            </div>
        </div>

            <input type="submit" value="Search" class="btn btn-default" />
            @Html.ActionLink("Show All", "Index", null, new { @class = "btn btn-default" })
</p>
}