CHY_Project/CHY_Project/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace CHY_Project.Models
{
    public class Album : Product
    {
        public String AlbumID { get; set;}

        [Required]
        [Display(Name ="Album Name")]
        public String AlbumName { get; set; }

        //NOTE: Do albums have artists in their own right or do they have artists by virtue of the songs on them?
        
        public virtual List<Artist> Artists { get; set; }

        public virtual List<Song> Songs { get; set; }

        //TODO: Find datatype for album art
        [DataType (DataType.ImageUrl)]
        public string AlbumArt { get; set;}
        //look for image in seed
    }
}

CHY_Project/CHY_Project/Models/AlbumViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CHY_Project.Models
{
    public class AlbumViewModel
    {
        public Int32 id { get; set; }

        [Display(Name = "Album Name")]
        public String AlbumName { get; set; }

        //NOTE: Do albums have artists in their own right or do they have artists by virtue of the songs on them?

        public virtual List<Artist> Artists { get; set; }

        public virtual List<Song> Songs { get; set; }

        //TODO: Find datatype for album art
        [DataType(DataType.ImageUrl)]
        public string AlbumArt { get; set; }

        public Decimal RegularPrice { get; set; }

        public Decimal DiscountPrice { get; set; }
    }
}

CHY_Project/CHY_Project/Controllers/AlbumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CHY_Project.Models;

namespace CHY_Project.Controllers
{
    public class AlbumsController : Controller
    {
        public enum AlbumSort { Name, Artist, Rating }

        private AppDbContext db = new AppDbContext();

        // GET: Albums
        public ActionResult Index()
        {

            List<Album> AllAlbums = db.Albums.ToList();
            ViewBag.AlbumCount = CountAlbums(AllAlbums);
            ViewBag.TotalAlbumCount = CountAlbums(AllAlbums);

            
            return View(db.Albums.ToList());
        }

        // GET: Albums/Details/5
        public ActionResult Details(int? id)
        {
            //TODO: make list of songs
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }
        [Authorize (Roles ="Manager")]
        // GET: Albums/Create
        public ActionResult Create()
        {
            Album album = new Album();
            ViewBag.AllArtists = GetAllArtists();
            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllSongs = GetAllSongs();
            return View();
        }
        [Authorize(Roles = "Manager")]
        // POST: Albums/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ContentID,RegularPrice,DiscountPrice,Featured,AlbumName,AlbumArt")] Album album, Int32[] Artists, Int32[] Genres, Int32[] Songs)
        {
            //if (ModelState.IsValid)
            //{
                
            //    db.Albums.Add(album);
            //    db.SaveChanges();
            //}

            if (Artists != null)
            {
                album.Artists = new List<Artist>();
                foreach (int Id in Artists)
                {

                    Artist artist = db.Artists.Find(Id);
                    
                    //Artist artist = db.Artists.Find(Convert.ToString(Id));
                    album.Artists.Add(artist);
                }
            }


            if (Genres != null)
            {
                album.Genres = new List<Genre>();
                //song.Genres = new List<Genre>();
                foreach (int Id in Genres)
                {
                    
                    Genre genre = db.Genres.Find(Id);
                    album.Genres.Add(genre);
                }
            }

            //TODO: Add logic to make sure a song can only be added to one album

            if (Songs != null)
            {
                album.Songs = new List<Song>();
                foreach (int Id in Songs)
                {
                    
                    //Song song = db.Songs.FirstOrDefault(i => i.ContentID == Id);
                    Song song = db.Songs.Find(Id);
                    album.Songs.Add(song);
                }
            }

            Guid guidAlbumProductID = Guid.NewGuid();
            Guid guidAlbumID = Guid.NewGuid();

            String stringAlbumProductID = guidAlbumProductID.ToString();
            String stringAlbumID = guidAlbumID.ToString();

            album.ProductID = stringAlbumProductID;
            album.AlbumID = stringAlbumID;
            if (ModelState.IsValid)
            {

                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AllArtists = GetAllArtists();
            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllSongs = GetAllSongs();
            return View(album);
        }
        [Authorize(Roles = "Manager")]
        // GET: Albums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.AllArtists = GetAllArtists();
            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllSongs = GetAllSongs();
            return View(album);
        }

        // POST: Albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ContentID,RegularPrice,DiscountPrice,Featured,AlbumName,AlbumArt")] Album album, String[] Artists, Int32[] Genres, String[] Songs)
        {
            if (ModelState.IsValid)
            {
                Album albumtochange = db.Albums.Find(album.ContentID);

                if (Songs != null)
                {
                    foreach (string Id in Songs)
                    {
                        Song song = db.Songs.FirstOrDefault(i => i.SongID == Id);
                        albumtochange.Songs.Add(song);
                    }
                }
                if (Artists != null)
                {
                    foreach (string Id in Artists)
                    {
                        Artist artist = db.Artists.FirstOrDefault(i => i.ArtistID == Id);
                        albumtochange.Artists.Add(artist);
                    }
                }
                if (Genres != null)
                {
                    album.Genres = new List<Genre>();
                    foreach (int Id in Genres)
                    {
                        Genre genre = db.Genres.Find(Id);
                        album.Genres.Add(genre);
                    }
                }

                //TODO: Uncomment once album art functionality built.
                //TODO: Add album art as a property above
                //albumtochange.AlbumArt = album.AlbumArt;
                albumtochange.RegularPrice = album.RegularPrice;
                albumtochange.DiscountPrice = album.DiscountPrice;
                albumtochange.Featured = album.Featured;
                albumtochange.AlbumName = album.AlbumName;
                albumtochange.AlbumArt = album.AlbumArt;

                db.Entry(albumtochange).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AllArtists = GetAllArtists();
            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllSongs = GetAllSongs();
            return View(album);
        }
        [Authorize(Roles = "Manager")]
        // GET: Albums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Albums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            album.Artists.Clear();
            db.Contents.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Album Search
        public ActionResult Search()
        {
            ViewBag.AllGenres = GetAllGenres();
            ViewBag.AllArtists = GetAllArtists();
            ViewBag.AllSongs = GetAllSongs();
            return View();
        }

        //Search Results
        public ActionResult SearchResults(string NameSearchString, string ArtistSearchString, Int32[] SelectedGenres, AlbumSort SelectedSort, SongsController.SortOrder SelectedSortOrder/*, TODO: Add parameter for Rating, once that is set up*/)
        {
            List<Album> SelectedAlbums = new List<Album>();
            List<Album> AllAlbums = db.Albums.ToList();

            var query = from a in db.Albums
                        select a;

            var qtest = query;

            if (NameSearchString != null && NameSearchString != "")
            {
                query = query.Where(a => a.AlbumName.Contains(NameSearchString));
            }

            if (ArtistSearchString != null && ArtistSearchString != "")
            {
                query = query.Where(a => a.Artists.Any(ar => ar.ArtistName.Contains(ArtistSearchString)));
            }

            if (qtest != query)
            {
                SelectedAlbums = query.ToList();
            }

            //TODO: Add rating search once that functionality is live

            List<Album> AlbumsInGenre;
            if (SelectedGenres != null)
            {
                foreach (int id in SelectedGenres)
                {
                    Genre genre = db.Genres.Find(id);

                    AlbumsInGenre = query.Where(a => a.Genres.Any(g => g.GenreID.Equals(id))).ToList();
                    foreach (Album a in AlbumsInGenre)
                    {
                        if (SelectedAlbums.Contains(a) == false)
                        {
                            SelectedAlbums.Add(a);
                        }
                    }
                }

CHY_Project/CHY_Project/Views/Albums/Create.cshtml
@model CHY_Project.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.AlbumName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumArt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumArt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumArt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegularPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegularPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegularPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscountPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiscountPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiscountPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Featured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Featured)
                    @Html.ValidationMessageFor(model => model.Featured, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-control">
            @Html.LabelFor(model => model.Artists, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Artists", (MultiSelectList)ViewBag.AllArtists, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Genres", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Songs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Songs", (MultiSelectList)ViewBag.AllSongs, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CHY_Project/CHY_Project/Views/Albums/Delete.cshtml
@model CHY_Project.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.RegularPrice)
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.RegularPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscountPrice)
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.DiscountPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Featured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Featured)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.AlbumName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CHY_Project/CHY_Project/Views/Albums/Details.cshtml
@model CHY_Project.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album @Html.DisplayFor(model => model.AlbumName)</h4>
    <hr />
    <div class="img-thumbnail">
        <img alt="@Model.AlbumName"
             src="@Model.AlbumArt" />
    </div>
    <table class="table table-bordered">
        <tr>
            <th>
                Artists
            </th>
        </tr>

        @foreach (var artist in Model.Artists)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => artist.ArtistName)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "Artists", new { id = artist.ContentID }, null)
                </td>
            </tr>
        }
    </table>
    @Html.ActionLink("Add to Cart", "AddtoCart", "Carts", new { id = Model.ContentID }, null)
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AlbumName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AlbumName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegularPrice)
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.RegularPrice)
        </dd>

        @if (Model.DiscountPrice < Model.RegularPrice)
        {
            <dt>
                @Html.DisplayNameFor(model => model.DiscountPrice)
            </dt>
            <dd>
                $@Html.DisplayFor(model => model.DiscountPrice)
            </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.Featured)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Featured)
        </dd>




    </dl>
    <table class="table table-bordered">
        <tr>
            <th>
                Songs
            </th>
        </tr>
        @foreach (var song in Model.Songs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => song.SongName)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "Songs", new { id = song.ContentID}, null)
                </td>
            </tr>
        }
    </table>
    <table class="table table-bordered">
        <tr>
            <th>
                Genres
            </th>
        </tr>
        @foreach (var genre in Model.Genres)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => genre.GenreName)
                </td>
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ContentID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CHY_Project/CHY_Project/Views/Albums/Edit.cshtml
@model CHY_Project.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ContentID)

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Artists, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Artists", (MultiSelectList)ViewBag.AllArtists, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlbumArt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlbumArt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AlbumArt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegularPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegularPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegularPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiscountPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiscountPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiscountPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Featured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Featured)
                    @Html.ValidationMessageFor(model => model.Featured, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Genres", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
            </div>
       </div>

        <div class="form-control">
            @Html.LabelFor(model => model.Songs, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("Songs", (MultiSelectList)ViewBag.AllSongs, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CHY_Project/CHY_Project/Views/Albums/Index.cshtml
@model IEnumerable<CHY_Project.Models.Album>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h3> Displaying @ViewBag.AlbumCount of @ViewBag.TotalAlbumCount Results</h3>

<p>
@Html.ActionLink("Search Albums", "Search", null, new { @class = "btn btn-default" })
</p>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AlbumName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Artists.First().ArtistName)
        </th>
        <th>
            Price
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AlbumName)
            </td>


            @*@foreach (var artist in item.Artists)
            {
                <td>
                    @Html.DisplayFor(modelItem => artist.ArtistName)
                </td>

            }*@

            @*NOTE: I changed this to the below so that it didn't mess up formatting by having a list of artists in one field. We can change it back if need be.*@

            <td>
                @Html.DisplayFor(modelItem => item.Artists.First().ArtistName)
            </td>

            <td>
                $@Html.DisplayFor(modelItem => item.DiscountPrice)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ContentID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ContentID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ContentID }) |
                @Html.ActionLink("Add to Cart", "AddtoCart", "Carts", new { id = item.ContentID }, null)
            </td>
        </tr>
    }

</table>

CHY_Project/CHY_Project/Views/Albums/Search.cshtml
@using CHY_Project.Controllers
@model CHY_Project.Models.Album

@{
    ViewBag.Title = "Album Search";
}

<h2>Album Search</h2>

@using (Html.BeginForm("SearchResults", "Albums", FormMethod.Get))
{
<p class="form-group">
        Album Title @Html.TextBox("NameSearchString", null, new { @class = "form-control" }) <br />
        Artist @Html.TextBox("ArtistSearchString", null, new { @class = "form-control" }) <br />

        <div class="form-control">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBox("SelectedGenres", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
            </div>
        </div>

    <div class="form-group">
        Sort By
        <div class="form-check">
            @Html.RadioButton("SelectedSort", AlbumsController.AlbumSort.Name, true, new { @class = "form-check-input" }) Name
        </div>
        <div class="form-check">
            @Html.RadioButton("SelectedSort", AlbumsController.AlbumSort.Artist, new { @class = "form-check-input" }) Artist
        </div>
        <div class="form-check">
            @Html.RadioButton("SelectedSort", SongsController.SongSort.Rating, new { @class = "form-check-input" }) Rating
        </div>
    </div>

    <div class="form-group">
        Order
        <div class="form-check">
            @Html.RadioButton("SelectedSortOrder", SongsController.SortOrder.Ascending, true, new { @class = "form-check-input" }) Ascending
        </div>
        <div class="form-check">
            @Html.RadioButton("SelectedSortOrder", SongsController.SortOrder.Descending, new { @class = "form-check-input" }) Descending
        </div>
    </div>

        <input type="submit" value="Search" class="btn btn-default" />
        @Html.ActionLink("Show All", "Index", null, new { @class = "btn btn-default" })
</p>
}